name: compendium
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.3.7
  flutter_bloc: ^8.1.4
  go_router: ^12.0.0
  hexcolor: ^2.0.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.0
  freezed: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
